In [15]:
import pandas as pd
from datasetz.core.load_dataset import load_embedded_dataset

ModuleNotFoundError: No module named 'datasetz'

In [12]:
DATASETS = ['wisconsin', 'bupa', 'bands', 'ionosphere', 'hepatitis', 'saheart',
            'haberman', 'housevotes', 'heart', 'australian', 'tic-tac-toe',
            'mammographic', 'monk-2', 'appendicitis', 'breast', 'crx']

In [13]:
for d in DATASETS:
    dataset = load_embedded_dataset('keel-binary-fast', d)

NameError: name 'load_embedded_dataset' is not defined

In [3]:
complexities_df = pd.read_csv('complexities.csv')

In [5]:
time_columns = [c for c in complexities_df.columns if "-time" in c]

In [ ]:
'f2', 't4', 'c1', 'n3', 'l2', 'density'

In [11]:
complexities_df[time_columns].mean().sort_values()

t2-time          0.000036
c1-time          0.000088
c2-time          0.000118
f2-time          0.000311
f3-time          0.000431
f1-time          0.000447
t4-time          0.001687
t3-time          0.001695
f4-time          0.008822
n2-time          0.009814
f1v-time         0.013929
n3-time          0.048440
l2-time          0.055594
l1-time          0.055877
lsc-time         0.078426
l3-time          0.099713
n4-time          0.100265
t1-time          0.319571
density-time     0.336880
n1-time          0.583608
hubs-time        0.672919
clsCoef-time    11.501390
dtype: float64

In [7]:
complexities_df.melt(time_columns)

,f1-time,f2-time,f3-time,f4-time,f1v-time,c1-time,c2-time,l1-time,l2-time,l3-time,...,t1-time,t2-time,t3-time,t4-time,clsCoef-time,hubs-time,density-time,lsc-time,variable,value
0,0.000333,0.000181,0.000392,0.003115,0.021765,0.000065,0.000073,0.014238,0.011372,0.015067,...,0.018858,0.000028,0.002491,0.001177,0.034276,0.016014,0.012088,0.001180,dataset_name,ionosphere
1,0.000266,0.000185,0.000379,0.003853,0.021445,0.000066,0.000072,0.014371,0.013920,0.017801,...,0.022180,0.000029,0.001235,0.001489,0.030755,0.015274,0.011925,0.008652,dataset_name,ionosphere
2,0.000249,0.000169,0.000361,0.002671,0.021689,0.000066,0.000069,0.014328,0.013161,0.017035,...,0.016979,0.000032,0.001296,0.001286,0.032821,0.015486,0.011984,0.001933,dataset_name,ionosphere
3,0.000252,0.000176,0.000388,0.003753,0.020937,0.000070,0.000072,0.013674,0.012974,0.016395,...,0.017896,0.000025,0.001226,0.001110,0.030336,0.016369,0.012127,0.001789,dataset_name,ionosphere
4,0.000221,0.000168,0.000382,0.003247,0.021489,0.000061,0.000075,0.014496,0.015072,0.018305,...,0.026961,0.000027,0.001117,0.001399,0.032331,0.016573,0.015982,0.001446,dataset_name,ionosphere
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7245,0.000173,0.000128,0.000224,0.000875,0.006921,0.000055,0.000059,0.002930,0.002935,0.003563,...,0.002679,0.000024,0.000661,0.000646,0.003084,0.002781,0.002215,0.000364,lsc,0.895625
7246,0.000179,0.000134,0.000230,0.000479,0.007082,0.000054,0.000059,0.002151,0.002225,0.003060,...,0.002535,0.000022,0.000668,0.000638,0.003011,0.002828,0.002256,0.000373,lsc,0.82125
7247,0.000174,0.000129,0.000223,0.000613,0.006941,0.000058,0.000059,0.002645,0.002559,0.003441,...,0.002509,0.000025,0.000683,0.000610,0.002985,0.002673,0.002257,0.000368,lsc,0.885
7248,0.000179,0.000133,0.000216,0.000620,0.007139,0.000057,0.000059,0.002977,0.002908,0.003864,...,0.002716,0.000023,0.000658,0.000631,0.003004,0.002675,0.002289,0.000378,lsc,0.859375
7249,0.000175,0.000132,0.000229,0.000341,0.007011,0.000057,0.000066,0.002107,0.002111,0.002975,...,0.002208,0.000022,0.000662,0.000636,0.002968,0.002825,0.002388,0.000389,lsc,0.836875